### ISSUE TITLE
Does not run in node

### ISSUE THREAD

**Issue by at0g** [webpack/mocha-loader#22]
The file to test:
```
// file test/spec.js
describe('test runner spec', function () {
	it('runs', function () {});
});
```

## The desired result

```
mocha
 test runner spec
    ✓ runs


  1 passing (9ms)
```

## Attempt 1 - Follow the readme...

```
npm i -g enhanced-require
enhanced-require 'mocha\!./test/spec.js'
```

Results in:
```
/usr/local/lib/node_modules/enhanced-require/lib/execLoaders.js:195
                if(err) throw err;
                              ^
Error: loader did not return a value
```

## Attempt 2 - Read source code...

[Presumably node is a supported target?](https://github.com/webpack/mocha-loader/blob/master/index.js#L27)

```
// file: webpack.config.js
module.exports = {
	target: 'node',
	entry: {
		main: 'mocha!./test/spec.js'
	},
	output: {
		path: 'build/',
		filename: '[name].js'
	}
};
```

I run `webpack` from the command line and see this (followed by many, many more errors)

```
WARNING in ./~/mocha-loader/EnhancedMocha.js
Critical dependencies:
29:24-37 the request of a dependency is an expression
 @ ./~/mocha-loader/EnhancedMocha.js 29:24-37
```

Is there something I missed?

**Comment by Marsup** [comment]
Been banging my head at it for while too with the same error, did you find something ?

**Comment by at0g** [comment]
I used karma instead - much easier

**Comment by Marsup** [comment]
I already use karma but I'd also like to run it with jsdom for a faster feedback loop and better compatibility with our CI.

**Comment by bmcorser** [comment]
Try:
```
webpack-dev-server 'mocha!./test.js' --output-filename test.js
```
Then visit [http://localhost:8080/webpack-dev-server/test](http://localhost:8080/webpack-dev-server/test)

**Comment by mr-mig** [comment]
I've being struggling with the same issue for a while. 
The goal is to be able to run tests **once** using mocha and node, without karma and phantomjs (think headless CI as a usecase).

I have 
```
entry: 'mocha!./test-index.js'
``` 
defined in webpack config, so that I can use it with the webpack-dev-server in a TDD mode in a separate browser tab.

Overriding `entry` in webpack config via cli parameter and adding `mocha-loader` as `externals` helped me to resolve this issue.

```
// deep inside webpack.test.config.js
externals: {'mocha-loader': true}
```

The resulting invocation to run the tests looks like that:
```bash
webpack \
  --config webpack.config.test.js \
  --entry ./test-index.js \
  --output-filename /tmp/tests.js \
  --target node \
  && mocha /tmp/tests.js
```

**Comment by tricoder42** [comment]
This is related to how webpack works, not mocha-loader. The example in README should be updated or fixed though.

When bundling for node environment, externals libraries shouldn't be included in bundle, because all can be loaded via `require` call. Webpack provides [`externals`](https://webpack.github.io/docs/configuration.html#externals) option to specify, which libraries should be omitted.

Package [`webpack-node-externals`](https://www.npmjs.com/package/webpack-node-externals) make configuration even more simple (copied from `webpack-node-externals` README):

```js
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    target: 'node', // in order to ignore built-in modules like path, fs, etc. 
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder 
    ...
};
```

This will definitely fix the approach in 2nd attempt. I'll leave this issue open, until we fix the example in README.
